name: Build the project

on: 
  push:
    branches: 
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node 
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Add env vars
        run: |
          cd packages/db
          npm install
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          cd ../..

          cd apps/user
            npm install
            echo "JWT_SECRET=${{ secrets.USER_APP_JWT_SECRET }}" >> .env
            echo "NEXTAUTH_URL=${{ secrets.USER_APP_NEXTAUTH_URL }}" >> .env
            echo "SECRET=${{ secrets.USER_APP_SECRET }}" >> .env
          
          cd ../bank
            npm install
            echo "UPSTASH_REDIS_REST_URL=${{ secrets.BANK_APP_UPSTASH_REDIS_REST_URL }}" >> .env
            echo "UPSTASH_REDIS_REST_TOKEN=${{ secrets.BANK_APP_UPSTASH_REDIS_REST_TOKEN }}" >> .env
            echo "SECRET=${{ secrets.BANK_APP_SECRET }}" >> .env
          cd ../..

      - name: Check Build
        run: npm run build
