name: Check linting and formatting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Check linting
        run: npm run lint:check